# Generated by Django 4.0.6 on 2022-07-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='Diseño', max_length=255)),
                ('teacher', models.CharField(default='Xavier Merino', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
